// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgAttempts.proto

package com.github.kylegagnon99;

public final class MsgAttemptsOuterClass {
  private MsgAttemptsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgAttemptsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:reactor.MsgAttempts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 numOfAttempts = 2;</code>
     * @return The numOfAttempts.
     */
    int getNumOfAttempts();
  }
  /**
   * Protobuf type {@code reactor.MsgAttempts}
   */
  public static final class MsgAttempts extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:reactor.MsgAttempts)
      MsgAttemptsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgAttempts.newBuilder() to construct.
    private MsgAttempts(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgAttempts() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgAttempts();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgAttempts(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 16: {

              numOfAttempts_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.kylegagnon99.MsgAttemptsOuterClass.internal_static_reactor_MsgAttempts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.kylegagnon99.MsgAttemptsOuterClass.internal_static_reactor_MsgAttempts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
            com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.class, com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.Builder.class);
    }

    public static final int NUMOFATTEMPTS_FIELD_NUMBER = 2;
    private int numOfAttempts_;
    /**
     * <code>int32 numOfAttempts = 2;</code>
     * @return The numOfAttempts.
     */
    @java.lang.Override
    public int getNumOfAttempts() {
      return numOfAttempts_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (numOfAttempts_ != 0) {
        output.writeInt32(2, numOfAttempts_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (numOfAttempts_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, numOfAttempts_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts)) {
        return super.equals(obj);
      }
      com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts other = (com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts) obj;

      if (getNumOfAttempts()
          != other.getNumOfAttempts()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMOFATTEMPTS_FIELD_NUMBER;
      hash = (53 * hash) + getNumOfAttempts();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code reactor.MsgAttempts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:reactor.MsgAttempts)
        com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttemptsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.kylegagnon99.MsgAttemptsOuterClass.internal_static_reactor_MsgAttempts_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.kylegagnon99.MsgAttemptsOuterClass.internal_static_reactor_MsgAttempts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.class, com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.Builder.class);
      }

      // Construct using reactor.MsgAttemptsOuterClass.MsgAttempts.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        numOfAttempts_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.kylegagnon99.MsgAttemptsOuterClass.internal_static_reactor_MsgAttempts_descriptor;
      }

      @java.lang.Override
      public com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts getDefaultInstanceForType() {
        return com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts build() {
        com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts buildPartial() {
        com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts result = new com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts(this);
        result.numOfAttempts_ = numOfAttempts_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts) {
          return mergeFrom((com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts other) {
        if (other == com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts.getDefaultInstance()) return this;
        if (other.getNumOfAttempts() != 0) {
          setNumOfAttempts(other.getNumOfAttempts());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
            com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int numOfAttempts_ ;
      /**
       * <code>int32 numOfAttempts = 2;</code>
       * @return The numOfAttempts.
       */
      @java.lang.Override
      public int getNumOfAttempts() {
        return numOfAttempts_;
      }
      /**
       * <code>int32 numOfAttempts = 2;</code>
       * @param value The numOfAttempts to set.
       * @return This builder for chaining.
       */
      public Builder setNumOfAttempts(int value) {

        numOfAttempts_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 numOfAttempts = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumOfAttempts() {

        numOfAttempts_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:reactor.MsgAttempts)
    }

    // @@protoc_insertion_point(class_scope:reactor.MsgAttempts)
    private static final com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts();
    }

    public static com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgAttempts>
        PARSER = new com.google.protobuf.AbstractParser<MsgAttempts>() {
      @java.lang.Override
      public MsgAttempts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgAttempts(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgAttempts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgAttempts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.kylegagnon99.MsgAttemptsOuterClass.MsgAttempts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reactor_MsgAttempts_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reactor_MsgAttempts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MsgAttempts.proto\022\007reactor\"$\n\013MsgAttem" +
      "pts\022\025\n\rnumOfAttempts\030\002 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reactor_MsgAttempts_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reactor_MsgAttempts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reactor_MsgAttempts_descriptor,
        new java.lang.String[] { "NumOfAttempts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
