// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReactorId.proto

package com.github.kylegagnon99;

public final class ReactorIdOuterClass {
  private ReactorIdOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReactorIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.github.kylegagnon99.ReactorId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 rid = 1;</code>
     * @return The rid.
     */
    long getRid();
  }
  /**
   * Protobuf type {@code com.github.kylegagnon99.ReactorId}
   */
  public static final class ReactorId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.github.kylegagnon99.ReactorId)
      ReactorIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReactorId.newBuilder() to construct.
    private ReactorId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReactorId() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ReactorId();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReactorId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              rid_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.kylegagnon99.ReactorIdOuterClass.internal_static_reactor_ReactorId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.kylegagnon99.ReactorIdOuterClass.internal_static_reactor_ReactorId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.class, com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.Builder.class);
    }

    public static final int RID_FIELD_NUMBER = 1;
    private long rid_;
    /**
     * <code>int64 rid = 1;</code>
     * @return The rid.
     */
    @java.lang.Override
    public long getRid() {
      return rid_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (rid_ != 0L) {
        output.writeInt64(1, rid_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (rid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, rid_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.kylegagnon99.ReactorIdOuterClass.ReactorId)) {
        return super.equals(obj);
      }
      com.github.kylegagnon99.ReactorIdOuterClass.ReactorId other = (com.github.kylegagnon99.ReactorIdOuterClass.ReactorId) obj;

      if (getRid()
          != other.getRid()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRid());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.kylegagnon99.ReactorIdOuterClass.ReactorId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.github.kylegagnon99.ReactorId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.github.kylegagnon99.ReactorId)
        com.github.kylegagnon99.ReactorIdOuterClass.ReactorIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.kylegagnon99.ReactorIdOuterClass.internal_static_reactor_ReactorId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.kylegagnon99.ReactorIdOuterClass.internal_static_reactor_ReactorId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.class, com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.Builder.class);
      }

      // Construct using com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        rid_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.kylegagnon99.ReactorIdOuterClass.internal_static_reactor_ReactorId_descriptor;
      }

      @java.lang.Override
      public com.github.kylegagnon99.ReactorIdOuterClass.ReactorId getDefaultInstanceForType() {
        return com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.getDefaultInstance();
      }

      @java.lang.Override
      public com.github.kylegagnon99.ReactorIdOuterClass.ReactorId build() {
        com.github.kylegagnon99.ReactorIdOuterClass.ReactorId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.github.kylegagnon99.ReactorIdOuterClass.ReactorId buildPartial() {
        com.github.kylegagnon99.ReactorIdOuterClass.ReactorId result = new com.github.kylegagnon99.ReactorIdOuterClass.ReactorId(this);
        result.rid_ = rid_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.kylegagnon99.ReactorIdOuterClass.ReactorId) {
          return mergeFrom((com.github.kylegagnon99.ReactorIdOuterClass.ReactorId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.kylegagnon99.ReactorIdOuterClass.ReactorId other) {
        if (other == com.github.kylegagnon99.ReactorIdOuterClass.ReactorId.getDefaultInstance()) return this;
        if (other.getRid() != 0L) {
          setRid(other.getRid());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.kylegagnon99.ReactorIdOuterClass.ReactorId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.kylegagnon99.ReactorIdOuterClass.ReactorId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long rid_ ;
      /**
       * <code>int64 rid = 1;</code>
       * @return The rid.
       */
      @java.lang.Override
      public long getRid() {
        return rid_;
      }
      /**
       * <code>int64 rid = 1;</code>
       * @param value The rid to set.
       * @return This builder for chaining.
       */
      public Builder setRid(long value) {

        rid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 rid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRid() {

        rid_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.github.kylegagnon99.ReactorId)
    }

    // @@protoc_insertion_point(class_scope:com.github.kylegagnon99.ReactorId)
    private static final com.github.kylegagnon99.ReactorIdOuterClass.ReactorId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.kylegagnon99.ReactorIdOuterClass.ReactorId();
    }

    public static com.github.kylegagnon99.ReactorIdOuterClass.ReactorId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReactorId>
        PARSER = new com.google.protobuf.AbstractParser<ReactorId>() {
      @java.lang.Override
      public ReactorId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReactorId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReactorId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReactorId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.github.kylegagnon99.ReactorIdOuterClass.ReactorId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_reactor_ReactorId_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_reactor_ReactorId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ReactorId.proto\022\007reactor\"\030\n\tReactorId\022" +
      "\013\n\003rid\030\001 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_reactor_ReactorId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_reactor_ReactorId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_reactor_ReactorId_descriptor,
        new java.lang.String[] { "Rid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
